// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace demotestscript
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Open_Browser_And_Navigate - Use 'Open_Browser_And_NavigateParams' to pass parameters into this method.
        /// </summary>
        public void Open_Browser_And_Navigate()
        {

            // Go to web page 'https://mirror.speridian.com/' using new browser instance
            this.UIMSNIndiaBreakingNewsWindow.LaunchUrl(new System.Uri(this.Open_Browser_And_NavigateParams.UIMSNIndiaBreakingNewsWindowUrl));
        }
        
        /// <summary>
        /// Enter_Username - Use 'Enter_UsernameParams' to pass parameters into this method.
        /// </summary>
        public void Enter_Username()
        {
            #region Variable Declarations
            HtmlEdit uITxtLoginNameEdit = this.UITheMirrorSperidianEmWindow.UITheMirrorSperidianEmDocument.UITxtLoginNameEdit;
            #endregion

            // Type 'ravi' in 'txtLoginName' text box
            uITxtLoginNameEdit.Text = this.Enter_UsernameParams.UITxtLoginNameEditText;
        }
        
        /// <summary>
        /// Enter_Password - Use 'Enter_PasswordParams' to pass parameters into this method.
        /// </summary>
        public void Enter_Password()
        {
            #region Variable Declarations
            HtmlEdit uITxtPasswordEdit = this.UITheMirrorSperidianEmWindow.UITheMirrorSperidianEmDocument.UITxtPasswordEdit;
            #endregion

            // Type '********' in 'txtPassword' text box
            uITxtPasswordEdit.Password = this.Enter_PasswordParams.UITxtPasswordEditPassword;
        }
        
        /// <summary>
        /// Click_On_Login_Button
        /// </summary>
        public void Click_On_Login_Button()
        {
            #region Variable Declarations
            HtmlInputButton uICtl00ContentPlaceHolButton = this.UITheMirrorSperidianEmWindow.UITheMirrorSperidianEmDocument.UICtl00ContentPlaceHolButton;
            #endregion

            // Click 'ctl00$ContentPlaceHolder1$btnGo' button
            Mouse.Click(uICtl00ContentPlaceHolButton, new Point(62, 24));
        }
        
        /// <summary>
        /// Verify_Invalid_Login_Text - Use 'Verify_Invalid_Login_TextExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Verify_Invalid_Login_Text()
        {
            #region Variable Declarations
            HtmlDiv uIInvalidLoginPane = this.UITheMirrorSperidianEmWindow.UITheMirrorSperidianEmDocument.UIInvalidLoginPane;
            #endregion

            // Verify that the 'InnerText' property of 'Invalid Login' pane equals 'Invalid Login'
            Assert.AreEqual(this.Verify_Invalid_Login_TextExpectedValues.UIInvalidLoginPaneInnerText, uIInvalidLoginPane.InnerText, "Invalid Login Text is not displayed");
        }
        
        #region Properties
        public virtual Open_Browser_And_NavigateParams Open_Browser_And_NavigateParams
        {
            get
            {
                if ((this.mOpen_Browser_And_NavigateParams == null))
                {
                    this.mOpen_Browser_And_NavigateParams = new Open_Browser_And_NavigateParams();
                }
                return this.mOpen_Browser_And_NavigateParams;
            }
        }
        
        public virtual Enter_UsernameParams Enter_UsernameParams
        {
            get
            {
                if ((this.mEnter_UsernameParams == null))
                {
                    this.mEnter_UsernameParams = new Enter_UsernameParams();
                }
                return this.mEnter_UsernameParams;
            }
        }
        
        public virtual Enter_PasswordParams Enter_PasswordParams
        {
            get
            {
                if ((this.mEnter_PasswordParams == null))
                {
                    this.mEnter_PasswordParams = new Enter_PasswordParams();
                }
                return this.mEnter_PasswordParams;
            }
        }
        
        public virtual Verify_Invalid_Login_TextExpectedValues Verify_Invalid_Login_TextExpectedValues
        {
            get
            {
                if ((this.mVerify_Invalid_Login_TextExpectedValues == null))
                {
                    this.mVerify_Invalid_Login_TextExpectedValues = new Verify_Invalid_Login_TextExpectedValues();
                }
                return this.mVerify_Invalid_Login_TextExpectedValues;
            }
        }
        
        public UIMSNIndiaBreakingNewsWindow UIMSNIndiaBreakingNewsWindow
        {
            get
            {
                if ((this.mUIMSNIndiaBreakingNewsWindow == null))
                {
                    this.mUIMSNIndiaBreakingNewsWindow = new UIMSNIndiaBreakingNewsWindow();
                }
                return this.mUIMSNIndiaBreakingNewsWindow;
            }
        }
        
        public UITheMirrorSperidianEmWindow UITheMirrorSperidianEmWindow
        {
            get
            {
                if ((this.mUITheMirrorSperidianEmWindow == null))
                {
                    this.mUITheMirrorSperidianEmWindow = new UITheMirrorSperidianEmWindow();
                }
                return this.mUITheMirrorSperidianEmWindow;
            }
        }
        #endregion
        
        #region Fields
        private Open_Browser_And_NavigateParams mOpen_Browser_And_NavigateParams;
        
        private Enter_UsernameParams mEnter_UsernameParams;
        
        private Enter_PasswordParams mEnter_PasswordParams;
        
        private Verify_Invalid_Login_TextExpectedValues mVerify_Invalid_Login_TextExpectedValues;
        
        private UIMSNIndiaBreakingNewsWindow mUIMSNIndiaBreakingNewsWindow;
        
        private UITheMirrorSperidianEmWindow mUITheMirrorSperidianEmWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Open_Browser_And_Navigate'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Open_Browser_And_NavigateParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://mirror.speridian.com/' using new browser instance
        /// </summary>
        public string UIMSNIndiaBreakingNewsWindowUrl = "https://mirror.speridian.com/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Enter_Username'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Enter_UsernameParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'ravi' in 'txtLoginName' text box
        /// </summary>
        public string UITxtLoginNameEditText = "ravi";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Enter_Password'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Enter_PasswordParams
    {
        
        #region Fields
        /// <summary>
        /// Type '********' in 'txtPassword' text box
        /// </summary>
        public string UITxtPasswordEditPassword = "b+1VYF8hlMSHZ6UXXrIwnHYhPlo4pK4d";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Verify_Invalid_Login_Text'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Verify_Invalid_Login_TextExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Invalid Login' pane equals 'Invalid Login'
        /// </summary>
        public string UIInvalidLoginPaneInnerText = "Invalid Login";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMSNIndiaBreakingNewsWindow : BrowserWindow
    {
        
        public UIMSNIndiaBreakingNewsWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN India | Breaking News, Entertainment, Latest Videos, Outlook";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN India | Breaking News, Entertainment, Latest Videos, Outlook");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITheMirrorSperidianEmWindow : BrowserWindow
    {
        
        public UITheMirrorSperidianEmWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "The Mirror - Speridian Employee Intranet";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("The Mirror - Speridian Employee Intranet");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UITheMirrorSperidianEmDocument UITheMirrorSperidianEmDocument
        {
            get
            {
                if ((this.mUITheMirrorSperidianEmDocument == null))
                {
                    this.mUITheMirrorSperidianEmDocument = new UITheMirrorSperidianEmDocument(this);
                }
                return this.mUITheMirrorSperidianEmDocument;
            }
        }
        #endregion
        
        #region Fields
        private UITheMirrorSperidianEmDocument mUITheMirrorSperidianEmDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITheMirrorSperidianEmDocument : HtmlDocument
    {
        
        public UITheMirrorSperidianEmDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "The Mirror - Speridian Employee Intranet";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pages/Login.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://mirror.speridian.com/Pages/Login.aspx";
            this.WindowTitles.Add("The Mirror - Speridian Employee Intranet");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UITxtLoginNameEdit
        {
            get
            {
                if ((this.mUITxtLoginNameEdit == null))
                {
                    this.mUITxtLoginNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITxtLoginNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_txtLoginName";
                    this.mUITxtLoginNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$txtLoginName";
                    this.mUITxtLoginNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUITxtLoginNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITxtLoginNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITxtLoginNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "waterMarkStyle";
                    this.mUITxtLoginNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$ContentPlaceHolder1$txtLogin";
                    this.mUITxtLoginNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUITxtLoginNameEdit.WindowTitles.Add("The Mirror - Speridian Employee Intranet");
                    #endregion
                }
                return this.mUITxtLoginNameEdit;
            }
        }
        
        public HtmlEdit UITxtPasswordEdit
        {
            get
            {
                if ((this.mUITxtPasswordEdit == null))
                {
                    this.mUITxtPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITxtPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_txtPassword";
                    this.mUITxtPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$txtPassword";
                    this.mUITxtPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUITxtPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUITxtPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITxtPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "waterMarkStyle";
                    this.mUITxtPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$ContentPlaceHolder1$txtPassw";
                    this.mUITxtPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUITxtPasswordEdit.WindowTitles.Add("The Mirror - Speridian Employee Intranet");
                    #endregion
                }
                return this.mUITxtPasswordEdit;
            }
        }
        
        public HtmlInputButton UICtl00ContentPlaceHolButton
        {
            get
            {
                if ((this.mUICtl00ContentPlaceHolButton == null))
                {
                    this.mUICtl00ContentPlaceHolButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceHolButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_btnGo";
                    this.mUICtl00ContentPlaceHolButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$btnGo";
                    this.mUICtl00ContentPlaceHolButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = null;
                    this.mUICtl00ContentPlaceHolButton.FilterProperties[HtmlButton.PropertyNames.Type] = "image";
                    this.mUICtl00ContentPlaceHolButton.FilterProperties["Src"] = "https://mirror.speridian.com/Images/button_submit.gif";
                    this.mUICtl00ContentPlaceHolButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceHolButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceHolButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"ctl00$ContentPlaceHolder1$btnGo\" t";
                    this.mUICtl00ContentPlaceHolButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "9";
                    this.mUICtl00ContentPlaceHolButton.WindowTitles.Add("The Mirror - Speridian Employee Intranet");
                    #endregion
                }
                return this.mUICtl00ContentPlaceHolButton;
            }
        }
        
        public HtmlDiv UIInvalidLoginPane
        {
            get
            {
                if ((this.mUIInvalidLoginPane == null))
                {
                    this.mUIInvalidLoginPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIInvalidLoginPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_valSummary";
                    this.mUIInvalidLoginPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIInvalidLoginPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Invalid Login";
                    this.mUIInvalidLoginPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIInvalidLoginPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIInvalidLoginPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"ctl00_ContentPlaceHolder1_valSummary\" style=\"color: red;\"";
                    this.mUIInvalidLoginPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
                    this.mUIInvalidLoginPane.WindowTitles.Add("The Mirror - Speridian Employee Intranet");
                    #endregion
                }
                return this.mUIInvalidLoginPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUITxtLoginNameEdit;
        
        private HtmlEdit mUITxtPasswordEdit;
        
        private HtmlInputButton mUICtl00ContentPlaceHolButton;
        
        private HtmlDiv mUIInvalidLoginPane;
        #endregion
    }
}
